---
title: "Draft Quarto document"
author: "Your Name"
format: html
---

```{r setup}
#| include: false #to remove code chunk from the html file
targets::tar_config_set(store = here::here("_targets")) # look in the _targets folder instead of the doc folder for the files
library(tidyverse)
library(targets)
library(tidymodels)
source(here::here("R/functions.R"))
lipidomics <- tar_read(lipidomics)
```

## Results

```{r}
tar_read(df_stats_by_metabolite) %>%
  mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) %>%
  select(Metabolite = metabolite, `Mean SD` = MeanSD) %>%
  knitr::kable(caption = "Descriptive statistics of the metabolites")
```

## Bulding the model

```{r}
lipidomics_wide <- lipidomics %>%
  column_values_to_snake_case(metabolite) %>%
  metabolites_to_wider()

lipidomics_wide
```

## Running multiple models

```{r}
lipidomics %>%
  split_by_metabolite() %>%
  map(generate_model_results) %>% # Add the function and apply to all datasets we just split
  list_rbind() %>% # to combine datasets on rows
  filter(str_detect(term, "metabolite_")) # Filter dataset to only keep metabolites
```
